---
    - hosts: tag_Name_DAMPOCAuthor
      user: ubuntu

      tasks:
      - name: Stop AEM service
        shell:
          sudo service aem61-author start
        register: cmdline
        become: true

      - name: Check startup log
        shell:
          cat {{ aem_home_directory }}/crx-quickstart/logs/startup.log | grep 'Quickstart started'
        register: cmdline
        failed_when: "cmdline.rc != 0"
        until: cmdline.rc == 0
        retries: 12
        delay: 10
